apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
  namespace: wordpress
  labels:
    app:  mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      containers:
      - name:  mysql
        image:  mysql:5.7
        env:
        - name:  MYSQL_ROOT_PASSWORD
          value:  password
        - name:  MYSQL_DATABASE
          value:  wordpress
        - name:  MYSQL_USER
          value:  wordpress
        - name:  MYSQL_PASSWORD
          value:  password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  3306
          name:  mysql
      restartPolicy: Always